import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Box, Typography, Stack, Button, Chip, Alert, TextField, MenuItem, Divider, Dialog, DialogTitle, DialogContent, DialogActions, Accordion, AccordionSummary, AccordionDetails, Tooltip } from '@mui/material';
import { ReactFlow, Background, Controls, Handle, Position, MarkerType, applyNodeChanges, type Node, type NodeProps, type Connection, type Edge } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { LabTheme, LabShell, LabIcon, Panel, Eyebrow } from '@playground/ui';
import { Tuple } from '../domain';
import { entities, entityName, tupleId, nodePrincipal, relationsFor } from './graph';
import './style.css';

type State = { mode: 'mock' | 'live'; tuples: Tuple[]; storeId?: string; modelId?: string };
type Check = { allowed: boolean; mode: string; path: string[] | null; pathTuples: Tuple[]; rbac: { allowed: boolean; role: string }; query: { user: string; relation: string; object: string } };
type EntityNode = Node<{ name: string; kind: string; id: string; highlighted: boolean }, 'entity'>;
const initialNodes: EntityNode[] = entities.map(e => ({ id: e.id, type: 'entity', position: { x: e.x, y: e.y }, data: { name: e.name, kind: e.kind, id: e.id, highlighted: false } }));
function Entity({ data, selected }: NodeProps<EntityNode>) {
  return <div className={`flow-node kind-${data.kind} ${selected ? 'selected' : ''} ${data.highlighted ? 'path-node' : ''}`}><Handle type="target" position={Position.Left} /><div className="node-icon"><LabIcon kind={data.kind} size={19} /></div><div className="node-kicker">{data.kind}</div><div className="node-label">{data.name}</div><div className="node-subtitle">{data.id}</div><Handle type="source" position={Position.Right} /></div>;
}
const nodeTypes = { entity: Entity };
async function api<T>(path: string, body?: unknown): Promise<T> {
  const response = await fetch(`/api/${path}`, body === undefined ? undefined : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const result = await response.json(); if (!response.ok) throw new Error(result.error); return result;
}
function SharingApp() {
  const [state, setState] = useState<State>({ mode: 'mock', tuples: [] });
  const [nodes, setNodes] = useState(initialNodes);
  const [selected, setSelected] = useState<string | null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [result, setResult] = useState<Check | null>(null);
  const [query, setQuery] = useState({ user: 'user:bob', relation: 'editor', object: 'document:1' });
  const [draft, setDraft] = useState<{ source: string; target: string; relation: string } | null>(null);
  const revision = useRef(0);
  useEffect(() => { let mounted = true; void api<State>('state').then(value => { if (mounted) setState(value); }).catch(e => { if (mounted) setError(String(e)); }); return () => { mounted = false; }; }, []);
  function invalidate() { revision.current++; setResult(null); }
  function changeQuery(patch: Partial<typeof query>) { setQuery(q => ({ ...q, ...patch })); invalidate(); }
  async function action(operation: () => Promise<void>) { setBusy(true); setError(''); try { await operation(); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  async function switchMode(mode: string) { invalidate(); await action(async () => { setState(await api<State>('mode', { mode })); setSelected(null); }); }
  async function mutate(operation: 'add' | 'delete', tuple: Tuple) {
    invalidate(); await action(async () => { const next = await api<State>('tuples', { operation, tuple }); setState(next); setSelected(null); setDraft(null); });
  }
  function connect(connection: Connection) {
    if (busy) return;
    const relations = relationsFor(connection.source, connection.target);
    if (!relations.length) { setError('この2つのnode間にはmodelで許可された関係がありません。人 → Team、または人・Team・Folder → resourceを選んでください。'); return; }
    setDraft({ source: connection.source, target: connection.target, relation: relations[0] });
  }
  const highlighted = useMemo(() => new Set(result?.allowed ? result.pathTuples.map(tupleId) : []), [result]);
  const pathNodes = new Set(result?.allowed ? result.pathTuples.flatMap(t => [t.user.replace('#member', ''), t.object]) : []);
  const shownNodes = nodes.map(n => ({ ...n, data: { ...n.data, highlighted: pathNodes.has(n.id) } }));
  const edges: Edge[] = state.tuples.map(t => ({ id: tupleId(t), source: t.user.replace('#member', ''), target: t.object, type: 'smoothstep', label: t.relation === 'parent' ? 'parent · inherits' : t.user.includes('#') ? `${t.relation} · members` : t.relation, selected: selected === tupleId(t), markerEnd: { type: MarkerType.ArrowClosed, color: highlighted.has(tupleId(t)) ? '#278779' : '#a7b0c6' }, style: { stroke: highlighted.has(tupleId(t)) ? '#278779' : selected === tupleId(t) ? '#555cb0' : '#a7b0c6', strokeWidth: highlighted.has(tupleId(t)) ? 3 : 1.7 }, animated: highlighted.has(tupleId(t)), data: { tuple: t }, ariaLabel: `${t.user} ${t.relation} ${t.object}` }));
  const selectedTuple = state.tuples.find(t => tupleId(t) === selected);
  const available = draft ? relationsFor(draft.source, draft.target) : [];
  return <LabShell number="03" title="Sharing is a relationship." subtitle="人、Team、Folder、Document。つながりを編集して、アクセス権が変わる瞬間を確かめる。" actions={<Stack direction="row"  sx={{ gap: 1 }}><Chip label={state.mode === 'live' ? '● LIVE / OpenFGA' : '● MOCK / Local evaluator'} color={state.mode === 'live' ? 'success' : 'default'} variant="outlined" /><Button size="small" variant="outlined" disabled={busy} onClick={() => void switchMode(state.mode === 'mock' ? 'live' : 'mock')}>{state.mode === 'mock' ? 'Connect real OpenFGA' : 'Use mock'}</Button></Stack>}>
    {error && <Alert severity="error" onClose={() => setError('')} sx={{ mb: 2 }}>{error}{error.includes('fetch') && ' — live利用時はOpenFGA serverを起動してください。'}</Alert>}
    <Box className="sharing-layout"><Box><Panel title="Relationship graph" subtitle="nodeを動かす・つなぐ・線を選んで切る。変更はそのまま認可に反映されます。" action={<Button variant="outlined" size="small" disabled={busy} onClick={() => setDraft({ source: 'user:bob', target: 'team:x', relation: 'member' })}>＋ Add relationship</Button>}>
      <Box className="graph-canvas" sx={{ height: 565 }}><ReactFlow nodes={shownNodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={changes => setNodes(current => applyNodeChanges(changes, current))} onConnect={connect} onEdgeClick={(_event, edge) => setSelected(edge.id)} onNodeClick={(_event, node) => { setSelected(null); if (node.id.startsWith('user:')) changeQuery({ user: node.id }); if (/^(folder|document):/.test(node.id)) changeQuery({ object: node.id }); }} onPaneClick={() => setSelected(null)} nodesConnectable={!busy} deleteKeyCode={null} fitView fitViewOptions={{ padding: .13 }} minZoom={.3} maxZoom={1.5}><Background gap={20} color="#dfe4f1" /><Controls showInteractive={false} /></ReactFlow></Box>
      <Box className="graph-legend">{['user', 'team', 'folder', 'document'].map(kind => <span key={kind}><LabIcon kind={kind} size={15} />{kind}</span>)}<span><i className="legend-dot" style={{ background: '#278779' }} />Authorization path</span></Box>
      <Box className={`relationship-inspector ${selectedTuple ? 'has-selection' : ''}`}>{selectedTuple ? <><Box><Eyebrow>SELECTED RELATIONSHIP</Eyebrow><Typography variant="body2"><strong>{entityName(selectedTuple.user)}</strong> <Chip label={selectedTuple.relation} sx={{ mx: 1 }} /> <strong>{entityName(selectedTuple.object)}</strong></Typography><Typography variant="caption" color="text.secondary">{selectedTuple.user} → {selectedTuple.object}</Typography></Box><Button color="error" variant="outlined" size="small" disabled={busy} onClick={() => void mutate('delete', selectedTuple)}>この関係を削除</Button></> : <Typography variant="body2" color="text.secondary">線をクリックすると、ここで関係を削除できます。node右の丸から別node左の丸へドラッグすると関係を追加できます。</Typography>}</Box>
    </Panel><Accordion disableGutters variant="outlined"><AccordionSummary expandIcon={<span>⌄</span>}><Typography variant="body2">Relationship tuples / {state.tuples.length} edges</Typography></AccordionSummary><AccordionDetails>{state.tuples.map(t => <Stack direction="row"   key={tupleId(t)} sx={{ py: .7 , alignItems: "center", justifyContent: "space-between" }}><Typography className="mono">{t.user} — {t.relation} → {t.object}</Typography><Tooltip title="グラフ上で選択"><Button size="small" onClick={() => setSelected(tupleId(t))}>選択</Button></Tooltip></Stack>)}</AccordionDetails></Accordion></Box>
    <Box component="aside"><Panel title="Check permission" subtitle="人とresourceのnodeをクリックしても選べます。"><Eyebrow>AUTHORIZATION, NOT AUTHENTICATION</Eyebrow><Stack component="form" spacing={2} sx={{ mt: 2 }} onSubmit={event => { event.preventDefault(); const version = revision.current; void action(async () => { const check = await api<Check>('check', query); if (version === revision.current) setResult(check); }); }}>
      <TextField select label="Mock user" value={query.user} onChange={e => changeQuery({ user: e.target.value })}>{entities.filter(e => e.kind === 'user').map(e => <MenuItem value={e.id} key={e.id}>{e.name}</MenuItem>)}</TextField><Stack direction="row"  sx={{ gap: 1.5 }}><TextField fullWidth select label="Can" value={query.relation} onChange={e => changeQuery({ relation: e.target.value })}>{[['editor', 'Edit'], ['viewer', 'View'], ['owner', 'Own']].map(([v, label]) => <MenuItem key={v} value={v}>{label}</MenuItem>)}</TextField><TextField fullWidth select label="Resource" value={query.object} onChange={e => changeQuery({ object: e.target.value })}>{entities.filter(e => ['document', 'folder'].includes(e.kind)).map(e => <MenuItem value={e.id} key={e.id}>{e.name}</MenuItem>)}</TextField></Stack><Button type="submit" variant="outlined" sx={{ alignSelf: "flex-start" }} disabled={busy} endIcon={<LabIcon kind="arrow" size={17} />}>Check permission</Button>
    </Stack><Divider sx={{ my: 2.5 }} />{result ? <><Alert severity={result.allowed ? 'success' : 'error'} icon={<LabIcon kind={result.allowed ? 'check' : 'graph'} />}><strong>{result.allowed ? 'ALLOWED' : 'DENIED'}</strong><br />{entityName(result.query.user)} → {result.query.relation} → {entityName(result.query.object)}</Alert><Typography variant="caption" color="text.secondary" sx={{ display: 'block', my: 1.5 }}>{result.mode === 'live' ? 'OpenFGA server decision' : 'MOCK local decision'}</Typography><ol className="path-steps">{(result.path ?? ['一致する認可経路がありません。']).map((step, i) => <li key={i}>{step}</li>)}</ol><Typography variant="caption" color="text.secondary">緑の経路は現在のtupleから計算した教育用の説明です。OpenFGA内部のtraceではありません。</Typography></> : <Box className="check-placeholder"><LabIcon kind="graph" size={28} /><Typography variant="body2">BobはDocument 1を編集できる？<br />Checkで、答えと経路を確かめる。</Typography></Box>}</Panel>
    <Panel title="RBAC vs ReBAC"><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>同じBobでも、TeamやFolderのつながりで答えが変わります。</Typography><Box className="comparison-row"><div><Eyebrow>GLOBAL RBAC</Eyebrow><Typography variant="h3">{result ? result.rbac.allowed ? 'ALLOWED' : 'DENIED' : '—'}</Typography><Typography variant="caption" color="text.secondary">{result ? `Role: ${result.rbac.role}` : '固定のglobal role'}</Typography></div><div><Eyebrow>RELATIONSHIPS</Eyebrow><Typography variant="h3" color={result?.allowed ? 'success.main' : 'primary'}>{result ? result.allowed ? 'ALLOWED' : 'DENIED' : '—'}</Typography><Typography variant="caption" color="text.secondary">resourceごとの関係</Typography></div></Box><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 2 }}>比較用RBACはAlice=editor / Bob=viewer / Carol=none。resource scopeを持たない単純なbaselineです。</Typography></Panel>
    <Panel title="Try cutting a connection"><Typography variant="body2" color="text.secondary">① Bobのedit権限をCheck<br />② Bob → Team Xのmember線を選んで削除<br />③ もう一度CheckするとDENIED<br />④ つなぎ直して権限が戻ることを確認</Typography></Panel></Box></Box>
    <Dialog open={!!draft} onClose={() => { if (!busy) setDraft(null); }} fullWidth maxWidth="xs"><DialogTitle>Add a relationship</DialogTitle><DialogContent><Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>誰が、どの関係で、何につながるかを選びます。</Typography>{draft && <Stack spacing={2}><TextField select label="From" value={draft.source} onChange={e => { const next = { ...draft, source: e.target.value }; setDraft({ ...next, relation: relationsFor(next.source, next.target)[0] || '' }); }}>{entities.map(e => <MenuItem key={e.id} value={e.id}>{e.name} ({e.kind})</MenuItem>)}</TextField><TextField select label="To" value={draft.target} onChange={e => { const next = { ...draft, target: e.target.value }; setDraft({ ...next, relation: relationsFor(next.source, next.target)[0] || '' }); }}>{entities.filter(e => e.kind !== 'user').map(e => <MenuItem key={e.id} value={e.id}>{e.name} ({e.kind})</MenuItem>)}</TextField><TextField select label="Relation" value={draft.relation} onChange={e => setDraft({ ...draft, relation: e.target.value })}>{available.map(r => <MenuItem key={r} value={r}>{r}</MenuItem>)}</TextField>{!available.length && <Alert severity="info">この組み合わせに追加できる関係はありません。</Alert>}{draft.source === 'team:x' && <Typography variant="caption" color="text.secondary">Team Xのmembers全員に共有します（team:x#member）。</Typography>}{error && <Alert severity="error">{error}</Alert>}</Stack>}</DialogContent><DialogActions sx={{ p: 3 }}><Button disabled={busy} onClick={() => setDraft(null)}>Cancel</Button><Button variant="outlined" disabled={busy || !draft || !available.includes(draft.relation as Tuple['relation'])} onClick={() => { if (draft) void mutate('add', Tuple.parse({ user: nodePrincipal(draft.source), relation: draft.relation, object: draft.target })); }}>Add relationship</Button></DialogActions></Dialog>
  </LabShell>;
}
createRoot(document.getElementById('root')!).render(<LabTheme><SharingApp /></LabTheme>);
