import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Checkbox, Chip, CircularProgress, Divider, FormControlLabel, LinearProgress, MenuItem, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { Eyebrow, LabIcon, LabShell, Panel } from '@playground/ui';
import { elapsed, scoreLabel } from './types';
import { plannedCalls, snapshotQuestions, type QuestionCount, type TriageAnswer, type TriageConfig, type TriageMode, type TriageModelId, type TriagePhase, type TriageQuestion, type TriageRun } from './triage-types';
import './triage.css';

const engines: TriageModelId[] = ['jev', 'llm-adapter'];
const modes: Record<TriageMode, { label: string; detail: string }> = {
  batch: { label: 'Batch / まとめて1回', detail: '同じIssueと独立した複数の問いを、1つのrequestで渡します。' },
  sequential: { label: 'Sequential / 1問ずつ', detail: '同じIssueを毎回渡し、1問ずつ順番に呼び出します。' },
  compare: { label: 'Compare / 両方式', detail: 'Batch → Sequentialの順で、同じ問いを比較します。' },
  sweep: { label: 'Sweep / 1・4・8・16問', detail: 'Batchだけを1、4、8、16問の順で実行します。' },
};
async function api<T>(path: string, body?: unknown, signal?: AbortSignal): Promise<T> {
  const response = await fetch(path, body === undefined ? { signal } : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal });
  const data = await response.json();
  if (!response.ok) throw Object.assign(new Error(typeof data.error === 'string' ? data.error : `Request failed (${response.status})`), { status: response.status });
  return data;
}
function exportRun(run: TriageRun) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(run, null, 2)], { type: 'application/json' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = `issue-triage-${run.id}.json`; anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function phaseName(phase: TriagePhase): string { return `${phase.modelName} · ${phase.strategy} · ${phase.questionCount}問`; }
function AnswerCard({ question, answer, phase, index }: { question: TriageQuestion; answer?: TriageAnswer; phase: TriagePhase; index: number }) {
  const hasReference = question.expectedOptionId !== null;
  const comparable = answer?.status === 'ok' && answer.matchesExpected !== null;
  return <Panel className="triage-answer"><Stack direction="row" sx={{ justifyContent: 'space-between', gap: 1, mb: 1.2 }}><Eyebrow>QUESTION {String(index + 1).padStart(2, '0')}</Eyebrow><Chip variant="outlined" label={!answer ? '結果なし' : answer.status === 'error' ? 'Error' : 'Answered'} color={answer?.status === 'error' ? 'error' : 'default'} /></Stack>
    <Typography variant="h3" sx={{ mb: 1.2 }}>{question.title}</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 1.5 }}>{question.instructions}</Typography>
    {answer?.status === 'error' ? <Alert severity="error">{answer.error || 'この問いの結果を取得できませんでした。'}</Alert> : answer ? <><Stack direction="row" sx={{ gap: .7, flexWrap: 'wrap', alignItems: 'center', mb: 1.5 }}><Chip label={answer.selectedOptionId || '選択なし'} color="primary" variant="outlined" />{comparable && <Chip label={answer.matchesExpected ? '参照解と一致' : '参照解と不一致'} color={answer.matchesExpected ? 'success' : 'warning'} variant="outlined" />}</Stack><Typography variant="body2" sx={{ fontWeight: 600, mb: 1.3 }}>{question.criteria[answer.selectedOptionId || '']?.split(/[：:]/)[0]}</Typography><Typography variant="caption" color="text.secondary">{phase.model === 'jev' ? 'Jev probabilities' : 'LLM生成確率 / 未校正'}</Typography><Stack spacing={.8} sx={{ mt: .8 }}>{answer.scores.map(score => <Box key={score.optionId}><Stack direction="row" sx={{ justifyContent: 'space-between', gap: 1 }}><Typography variant="caption">{score.optionId}</Typography><Typography variant="caption" className="mono">{scoreLabel(score.score)}</Typography></Stack><LinearProgress variant="determinate" value={Math.min(100, Math.max(0, score.score * 100))} color={score.optionId === answer.selectedOptionId ? 'primary' : 'secondary'} sx={{ height: 5, borderRadius: 4, bgcolor: '#eef0f6' }} /></Box>)}</Stack>{phase.model === 'jev' && typeof answer.confidence === 'number' && <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>Jev confidence: {scoreLabel(answer.confidence)} · 正解の保証ではありません</Typography>}</> : <Typography variant="body2" color="text.secondary">このphaseに対応するanswerがありません。</Typography>}
    <Divider sx={{ my: 1.7 }} /><Typography variant="caption" color="text.secondary">{hasReference ? `参照解: ${question.expectedOptionId} · ${question.basis === 'text' ? '本文に根拠あり' : '人間の判断を含む'}` : question.rationale ? '参照解なし / 人間の判断を含む観点' : '参照解なし / 自動採点の対象外です'}</Typography>{question.rationale && <Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>{question.rationale}</Typography>}
    <Accordion disableGutters elevation={0} sx={{ mt: 1 }}><AccordionSummary expandIcon={<span>⌄</span>}><Typography variant="caption">この実行の判断基準</Typography></AccordionSummary><AccordionDetails><Stack spacing={1}>{Object.entries(question.criteria).map(([option, criteria]) => <Box key={option}><Typography variant="caption" sx={{ fontWeight: 650 }}>{option}</Typography><Typography variant="body2" color="text.secondary">{criteria}</Typography></Box>)}</Stack></AccordionDetails></Accordion>
  </Panel>;
}

export function TriageWorkbench({ navigation }: { navigation: ReactNode }) {
  const [config, setConfig] = useState<TriageConfig | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [text, setText] = useState(''), [questions, setQuestions] = useState<TriageQuestion[]>([]);
  const [count, setCount] = useState<QuestionCount>(16), [mode, setMode] = useState<TriageMode>('batch'), [models, setModels] = useState<TriageModelId[]>(['jev']);
  const [starting, setStarting] = useState(false), [job, setJob] = useState<TriageRun | null>(null), [history, setHistory] = useState<TriageRun[]>([]);
  const [viewId, setViewId] = useState<string | null>(null), [chosenPhase, setChosenPhase] = useState<number | null>(null);
  const initialized = useRef(false);
  async function refreshConfig() {
    setLoading(true); setError('');
    try { const next = await api<TriageConfig>('/api/triage/config'); setConfig(next); if (!initialized.current) { setText(next.preset.text); setQuestions(structuredClone(next.preset.questions)); initialized.current = true; } } catch (reason) { setError(String(reason)); } finally { setLoading(false); }
  }
  useEffect(() => { void refreshConfig(); }, []);
  useEffect(() => {
    if (!job || job.status !== 'running') return;
    const controller = new AbortController(); const id = job.id; let timer: ReturnType<typeof setTimeout>;
    async function poll() { try { const next = await api<TriageRun>(`/api/runs/${encodeURIComponent(id)}`, undefined, controller.signal); if (!controller.signal.aborted) { setJob(next); if (next.status === 'running') timer = setTimeout(() => void poll(), 400); } } catch (reason) { if (!controller.signal.aborted) { setError(String(reason)); if (reason instanceof Error && 'status' in reason && reason.status === 404) setJob(current => current?.id === id ? { ...current, status: 'failed', error: 'Serverからrunが見つかりません。新しく実行してください。' } : current); else timer = setTimeout(() => void poll(), 1500); } } }
    timer = setTimeout(() => void poll(), 400); return () => { controller.abort(); clearTimeout(timer); };
  }, [job?.id, job?.status]);
  useEffect(() => { if (job && job.status !== 'running') setHistory(current => [job, ...current.filter(run => run.id !== job.id)].slice(0, 8)); }, [job]);
  const busy = starting || job?.status === 'running';
  const view = (viewId ? history.find(run => run.id === viewId) : job) || null;
  const phaseIndex = chosenPhase === null ? Math.max(0, (view?.results.length || 0) - 1) : chosenPhase;
  const phase = view?.results[phaseIndex];
  const runQuestions = view?.questions.slice(0, phase?.questionCount || view.questionCount) || [];
  const draftSnapshot = snapshotQuestions(text, questions, config?.preset);
  const effectiveCount: QuestionCount = mode === 'sweep' ? 16 : count;
  const edits = draftSnapshot.filter((question, index) => config?.preset.questions[index]?.expectedOptionId !== null && question.expectedOptionId === null).length;
  const missing = models.filter(id => !config?.models.find(model => model.id === id)?.available);
  const ready = !loading && !busy && models.length > 0 && missing.length === 0 && text.trim().length > 0 && questions.length === 16 && draftSnapshot.every(question => question.instructions.trim() && Object.keys(question.criteria).length >= 2 && Object.values(question.criteria).every(value => value.trim()));
  const callCount = plannedCalls(mode, effectiveCount, models.length);
  const maxElapsed = Math.max(1, ...(view?.results.map(result => result.elapsedMs) || []));
  function updateQuestion(id: string, patch: Partial<TriageQuestion>) { setQuestions(current => current.map(question => question.id === id ? { ...question, ...patch } : question)); }
  async function start() {
    if (!ready) return;
    setStarting(true); setError('');
    try { const run = await api<TriageRun>('/api/triage/runs', { text, questions: draftSnapshot, questionCount: effectiveCount, models: [...models], mode }); setJob(run); setViewId(null); setChosenPhase(null); } catch (reason) { setError(String(reason)); } finally { setStarting(false); }
  }
  return <LabShell number="04" title="One issue. Sixteen questions." subtitle="Issueを共有stateにして、独立した複数の観点を一度に判断する。Jevのbatchと1問ずつの呼び出しを観察する。" actions={navigation}>
    {error && <Alert severity="error" onClose={() => setError('')} sx={{ mb: 2 }}>{error}</Alert>}
    <Box className="workbench-toolbar"><Box><Eyebrow>ISSUE TRIAGE / MULTIPLE INDEPENDENT DECISIONS</Eyebrow><Typography variant="body2" color="text.secondary">各問いは同じstateを読みます。別の問いの答えを参照する依存関係は持てません。Batchの回答は、requestが完了した時点でまとめて表示します。</Typography></Box><Button variant="outlined" disabled={loading || !!busy} onClick={() => void refreshConfig()}>{loading ? 'Checking setup…' : 'Refresh setup'}</Button></Box>
    <Box className="triage-layout"><Box component="aside"><Panel title="Issue & experiment" subtitle={config?.preset.title || 'Loading preset…'}>
      <Stack spacing={2} component="form" onSubmit={event => { event.preventDefault(); void start(); }}><TextField label="Shared issue / state" multiline minRows={10} maxRows={24} required value={text} disabled={!!busy} onChange={event => setText(event.target.value)} />
        <Stack direction="row" sx={{ gap: 1 }}><TextField select fullWidth label="Execution mode" value={mode} disabled={!!busy} onChange={event => setMode(event.target.value as TriageMode)}>{Object.entries(modes).map(([value, description]) => <MenuItem key={value} value={value}>{description.label}</MenuItem>)}</TextField><TextField select label="Questions" value={effectiveCount} disabled={!!busy || mode === 'sweep'} sx={{ minWidth: 94 }} onChange={event => setCount(Number(event.target.value) as QuestionCount)}>{[1, 4, 8, 16].map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Stack>
        <Typography variant="caption" color="text.secondary">{modes[mode].detail} {mode === 'sweep' ? '各サイズで先頭N問を使用します。' : `先頭${effectiveCount}問を使用します。`}</Typography><Divider />
        <Typography variant="h3">Decision engines</Typography><Box>{engines.map(id => config?.models.find(model => model.id === id)).filter(model => !!model).map(model => <Box className="model-setup" key={model.id}><FormControlLabel control={<Checkbox size="small" checked={models.includes(model.id as TriageModelId)} disabled={!!busy} onChange={event => setModels(current => event.target.checked ? [...current, model.id as TriageModelId] : current.filter(id => id !== model.id))} />} label={<Typography variant="body2" sx={{ fontWeight: 650 }}>{model.name}</Typography>} /><Chip variant="outlined" label={model.available ? 'Ready' : 'Setup required'} color={model.available ? 'success' : 'warning'} /><Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>{model.detail}</Typography></Box>)}</Box>
        {!!missing.length && !loading && <Alert severity="info">{missing.includes('jev') ? 'Jevはserverの.envにTYPESAFE_API_KEYが必要です。' : 'AdapterはREADMEのprovider設定が必要です。Codexでは保存済みCLIログインを使います。'} 設定後にserverを再起動してください。keyはこの画面に入力しません。</Alert>}
        <Box className="triage-call-budget"><Typography variant="body2"><strong>{callCount} calls</strong> · {models.length} engine{models.length === 1 ? '' : 's'} · {mode === 'sweep' ? '1 / 4 / 8 / 16 questions' : `${effectiveCount} questions`}</Typography><Typography variant="caption" color="text.secondary">複数engineは選択した順に実行します。通信量・利用枠は各providerに従います。</Typography></Box>
        {!!edits && <Alert severity="info">編集により{edits}問の参照解を外しました。変更後の入力を元の参照解で採点しません。</Alert>}
        <Stack direction="row" sx={{ gap: 1, alignItems: 'center', flexWrap: 'wrap' }}><Button type="submit" variant="outlined" startIcon={busy ? <CircularProgress size={13} /> : <LabIcon kind="play" size={14} />} disabled={!ready}>{busy ? 'Running…' : 'Run triage'}</Button><Button disabled={!!busy || !config} onClick={() => { if (config) { setText(config.preset.text); setQuestions(structuredClone(config.preset.questions)); } }}>Reset preset</Button></Stack>
      </Stack>
    </Panel><Panel title="Question definitions" subtitle="instructionsと候補ごとのcriteriaを編集できます。問いの順序は固定です。">
      {questions.map((question, index) => <Accordion disableGutters elevation={0} key={question.id} className="triage-question-editor"><AccordionSummary expandIcon={<span>⌄</span>}><Stack direction="row" sx={{ alignItems: 'center', gap: 1 }}><span className={`triage-question-number ${index < effectiveCount ? 'included' : ''}`}>{String(index + 1).padStart(2, '0')}</span><Typography variant="body2">{question.title}</Typography></Stack></AccordionSummary><AccordionDetails><Stack spacing={1.5}><TextField label={`Q${index + 1} instructions`} multiline minRows={2} fullWidth value={question.instructions} disabled={!!busy} onChange={event => updateQuestion(question.id, { instructions: event.target.value })} />{Object.entries(question.criteria).map(([option, criteria]) => <TextField key={option} label={`Q${index + 1} criteria · ${option}`} multiline minRows={2} fullWidth value={criteria} disabled={!!busy} onChange={event => updateQuestion(question.id, { criteria: { ...question.criteria, [option]: event.target.value } })} />)}<Typography variant="caption" color="text.secondary">{draftSnapshot[index]?.expectedOptionId === null ? '参照解なし（編集後、または人間の判断が必要な問い）' : `参照解: ${question.expectedOptionId} / ${question.basis === 'text' ? '本文の根拠' : '人間の判断'}`}</Typography></Stack></AccordionDetails></Accordion>)}
    </Panel></Box>
    <Box className="triage-results"><Panel title="Run overview" action={view && <Button variant="outlined" onClick={() => exportRun(view)}>Export JSON ↓</Button>}>
      <Stack direction="row" sx={{ gap: 1, flexWrap: 'wrap', alignItems: 'center', mb: 1.5 }}><Chip label={view?.status || 'Ready to explore'} color={view?.status === 'failed' ? 'error' : view?.status === 'completed' ? 'success' : 'default'} variant="outlined" />{view && <Typography variant="caption" color="text.secondary">{new Date(view.createdAt).toLocaleString()} · {view.mode}</Typography>}</Stack>
      {view ? <><LinearProgress variant="determinate" value={Math.min(100, 100 * view.progress.completedCalls / Math.max(1, view.progress.totalCalls))} sx={{ height: 6, borderRadius: 3, mb: 1.2 }} /><Typography variant="body2">{view.progress.completedCalls} / {view.progress.totalCalls} calls processed（失敗を含む）</Typography><Typography variant="caption" color="text.secondary">{view.progress.current}</Typography>{view.error && <Alert severity="error" sx={{ mt: 1.5 }}>{view.error}</Alert>}</> : <Typography variant="body2" color="text.secondary">まずBatchで16問。次にCompareやSweepで、呼び出し方と問いの数による違いを確かめてください。</Typography>}
      <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1.5 }}>測定は通信・SDK / Codex起動込みの経過時間です。モデル内部の実行時間ではありません。初回・実行順序・負荷の影響を受けます。</Typography>
      {!!history.length && <TextField select label="Run history / このタブ内の最新8件" value={viewId || ''} size="small" fullWidth sx={{ mt: 2 }} onChange={event => { setViewId(event.target.value || null); setChosenPhase(null); }}><MenuItem value="">Current run</MenuItem>{history.map(run => <MenuItem key={run.id} value={run.id}>{new Date(run.createdAt).toLocaleTimeString()} · {run.mode} · {run.questionCount}問 · {run.status}</MenuItem>)}</TextField>}
    </Panel>
    <Panel title="Timing comparison" subtitle="同じrun内の完了したphase。棒の長さは経過時間を表します。">
      {!view?.results.length ? <Typography variant="body2" color="text.secondary">phaseが完了すると、測定値がここに追加されます。</Typography> : <><Stack spacing={1.5} sx={{ mb: 2.5 }}>{view.results.map((result, index) => <Box key={index}><Stack direction="row" sx={{ justifyContent: 'space-between', gap: 1, mb: .5 }}><Typography variant="caption">{phaseName(result)}</Typography><Typography variant="caption" className="mono">{elapsed(result.elapsedMs)}</Typography></Stack><LinearProgress variant="determinate" value={Math.max(0, result.elapsedMs / maxElapsed * 100)} color={result.status === 'ok' ? result.strategy === 'batch' ? 'primary' : 'secondary' : 'warning'} sx={{ height: 7, borderRadius: 3, bgcolor: '#f0f2f7' }} /></Box>)}</Stack><TableContainer><Table size="small" aria-label="Triage phase timing"><TableHead><TableRow><TableCell>Engine / mode</TableCell><TableCell align="right">問数</TableCell><TableCell align="right">Elapsed</TableCell><TableCell align="right">Calls 成功/試行</TableCell><TableCell align="right">参照解一致</TableCell><TableCell align="right">Errors</TableCell></TableRow></TableHead><TableBody>{view.results.map((result, index) => { const references = result.answers.filter(answer => answer.status === 'ok' && answer.matchesExpected !== null); return <TableRow key={index} selected={phaseIndex === index}><TableCell><Button sx={{ whiteSpace: 'normal', textAlign: 'left', justifyContent: 'flex-start', px: 0 }} onClick={() => setChosenPhase(index)}>{result.modelName}<br />{result.strategy} · {result.status}</Button></TableCell><TableCell align="right">{result.questionCount}</TableCell><TableCell align="right">{elapsed(result.elapsedMs)}</TableCell><TableCell align="right">{result.completedCalls}/{result.requestCount}</TableCell><TableCell align="right">{references.length ? `${references.filter(answer => answer.matchesExpected).length}/${references.length}` : '—'}</TableCell><TableCell align="right">{result.answers.filter(answer => answer.status === 'error').length}</TableCell></TableRow>; })}</TableBody></Table></TableContainer><Typography variant="caption" color="text.secondary">CallsはSDK呼び出しの成功数/試行数です。設定不備で呼び出さなかった場合は0です。一致率は参照解のある有効な回答だけが対象です。エラーと参照解なしの問いを分けて確認してください。</Typography></>}
    </Panel>
    <Panel title="Decisions" subtitle="選択したphaseの実行時snapshotから表示します。左の編集内容とは独立しています。">
      {view && !!view.results.length && <Stack direction="row" sx={{ gap: 1, mb: 2, alignItems: 'center' }}><TextField select label="Completed phase" value={phaseIndex} fullWidth onChange={event => setChosenPhase(Number(event.target.value))}>{view.results.map((result, index) => <MenuItem value={index} key={index}>{phaseName(result)} · {result.status}</MenuItem>)}</TextField><Button onClick={() => setChosenPhase(null)} disabled={chosenPhase === null}>Latest</Button></Stack>}
      {!phase ? <Box className="triage-empty"><LabIcon kind="graph" size={28} /><Typography variant="body2" color="text.secondary">まだ完了したphaseはありません。Batchはすべての回答をまとめて受け取ります。</Typography></Box> : <><Stack direction="row" sx={{ gap: .8, flexWrap: 'wrap', mb: 1.5 }}><Chip label={phase.status} variant="outlined" color={phase.status === 'ok' ? 'success' : 'warning'} /><Chip label={`${phase.answers.length} answers`} variant="outlined" /><Typography variant="caption" color="text.secondary">{phase.providerModel || phase.requestedModel}</Typography></Stack>{phase.error && <Alert severity="error" sx={{ mb: 1.5 }}>{phase.error}</Alert>}<Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 2 }}>{phase.model === 'jev' ? 'Jevのprobabilities / confidenceと、参照解への一致を分けて観察します。' : 'Adapterの確率はLLMが生成した未校正の値です。Jevのprobabilitiesや性能を再現するものではありません。'}</Typography><Box className="triage-answer-grid">{runQuestions.map((question, index) => <AnswerCard key={question.id} index={index} question={question} answer={phase.answers.find(answer => answer.questionId === question.id)} phase={phase} />)}</Box></>}
      {view && <Accordion disableGutters elevation={0}><AccordionSummary expandIcon={<span>⌄</span>}><Typography variant="caption">実行時のIssue・問い・request log</Typography></AccordionSummary><AccordionDetails><Typography variant="caption">Immutable shared state</Typography><pre className="code-block">{view.text}</pre><Typography variant="caption">Question snapshot</Typography><pre className="code-block">{JSON.stringify(runQuestions, null, 2)}</pre><Typography variant="caption">Selected phase calls</Typography><pre className="code-block">{JSON.stringify(phase?.calls || [], null, 2)}</pre></AccordionDetails></Accordion>}
    </Panel></Box></Box>
  </LabShell>;
}
